package hr.ferit.srdandragas.kunst.model

data class Data(
    val id : Int = 0,
    val accession_number : String = "",
    val share_license_status : String = "",
    val tombstone : String = "",
    val current_location : String = "",
    val title : String = "",
    val title_in_original_language : String = "",
    val series : String = "",
    val series_in_original_language : String = "",
    val creation_date : String = "",
    val creation_date_earliest : Int = 0,
    val creation_date_latest: Int = 0,
    val creators : List<Creators> = listOf(),
    val culture : List<String> = listOf(),
    val technique : String = "",
    val support_materials : List<SupportMaterials> = listOf(),
    val department : String = "",
    val collection : String = "",
    val type : String = "",
    val measurements : String = "",
    val dimensions : Dimensions = Dimensions(Sheet(0.0, 0.0)),
    val state_of_the_work : String = "",
    val edition_of_the_work : String = "",
    val creditline : String = "",
    val copyright : String = "",
    val inscriptions : List<Inscriptions> = listOf(),
    val exhibitions : Exhibitions = Exhibitions(listOf(), listOf()),
    val provenance : List<Provenance> = listOf(),
    val find_spot : String = "",
    val related_works : List<RelatedWorks> = listOf(),
    val fun_fact : String = "",
    val digital_description : String = "",
    val wall_description : String = "",
    val citations : List<Citations> = listOf(),
    val catalogue_raisonne : String = "",
    val url : String = "",
    val images : Images = Images(Web("","","","",""), Print("","","","",""),Full("","","","","")),
    val updated_at : String = ""
)